# Generated by Django 6.0.1 on 2026-01-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_order_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
