# Generated by Django 6.0.1 on 2026-01-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
    ]
